image: maven:eclipse-temurin

stages:
  - build-backend
  - test-backend
  - package-backend
  - install-frontend
  - test-frontend

build-backend:
  stage: build-backend
  script:
    - mvn compile

test-backend:
  stage: test-backend
  script:
    - mvn verify
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml

package-backend:
  stage: package-backend
  script:
    - mvn clean package

install-frontend:
  image: node:latest
  stage: install-frontend
  script:
    - cd quizAcademyFrontend
    - npm i
  artifacts:
    paths:
      - node_modules/
      - dist/
    expire_in: 30 days

test-frontend:
  image: node:latest
  stage: test-frontend
  script:
    - cd quizAcademyFrontend
    - npm install
    - npm run test:unit

