package edu.ntnu.service;

import edu.ntnu.dao.questions.DragDropQuestionDAO;
import edu.ntnu.dao.questions.TrueFalseQuestionDAO;
import edu.ntnu.dto.QuizDTO;
import edu.ntnu.dto.questions.QuestionDTO;
import edu.ntnu.mapper.QuizMapper;
import edu.ntnu.model.Quiz;
import edu.ntnu.model.questions.MultipleChoiceQuestion;
import edu.ntnu.model.questions.TextInputQuestion;
import edu.ntnu.repository.QuizRepository;
import edu.ntnu.repository.questions.DragDropQuestionDAORepository;
import edu.ntnu.repository.questions.MultipleChoiceQuestionRepository;
import edu.ntnu.repository.questions.TextInputQuestionRepository;
import edu.ntnu.repository.questions.TrueFalseQuestionDAORepository;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;
import org.hibernate.exception.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;

@Service
public class QuizService {
  private final QuizRepository quizRepository;
  private final MultipleChoiceQuestionRepository multipleChoiceRepository;
  private final TextInputQuestionRepository textInputRepository;
  private final DragDropQuestionDAORepository dragDropRepository;
  private final TrueFalseQuestionDAORepository trueFalseRepository;
  private final QuestionService questionService;
  private final QuizMapper quizMapper;
  private final Logger logger = Logger.getLogger(QuizService.class.getName());

  @Autowired
  public QuizService(
      QuizRepository quizRepository,
      MultipleChoiceQuestionRepository multipleChoiceRepository,
      TextInputQuestionRepository textInputRepository,
      DragDropQuestionDAORepository dragDropRepository,
      TrueFalseQuestionDAORepository trueFalseRepository,
      QuizMapper quizMapper,
      QuestionService questionService)
  {
    this.quizRepository = quizRepository;
    this.multipleChoiceRepository = multipleChoiceRepository;
    this.textInputRepository = textInputRepository;
    this.dragDropRepository = dragDropRepository;
    this.trueFalseRepository = trueFalseRepository;
    this.quizMapper = quizMapper;
    this.questionService = questionService;
  }

  public ResponseEntity<QuizDTO> getQuiz(Long quizId) {
   try {
    Quiz quiz = quizRepository.findByQuizId(quizId);
    QuizDTO quizDTO = quizMapper.toQuizDTO(quiz);

    if (quizDTO != null) {
      logger.info("Quiz with id " + quizId + " found. Returning quiz.");
      return ResponseEntity.ok(quizDTO);
    } else {
      logger.info("Quiz with id " + quizId + " not found.");
      return ResponseEntity.notFound().build();
    }
  } catch (Exception e) {
    logger.severe("An error occurred while getting quiz with id " + quizId + ": " + e.getMessage());
    return ResponseEntity.status(500).build();
  }
  }

  public ResponseEntity<Iterable<QuizDTO>> getAllQuizzes(String username) {
    try {
      // Get all quizzes from the database
      Iterable<Quiz> quizzes = quizRepository.findAllByUser_Username(username);

      // Convert quizzes to DTOs
      if (quizzes != null) {
        List<QuizDTO> quizDTOs = new ArrayList<>();
        for (Quiz quiz : quizzes) {
          quizDTOs.add(quizMapper.toQuizDTO(quiz));
        }

        int numQuizzes = quizDTOs.size();
        logger.info(numQuizzes + " quizzes found. Returning quizzes.");
        return ResponseEntity.ok(quizDTOs);
      } else {
        logger.info("No quizzes found.");
        return ResponseEntity.notFound().build();
      }
    } catch (Exception e) {
      logger.severe("An error occurred while getting all quizzes: " + e.getMessage());
      return ResponseEntity.status(500).build();
    }
  }

  public ResponseEntity<QuizDTO> createQuiz(QuizDTO quizDTO) {
    try {
      // Map DTO to entity without ID. ID is generated by database.
      Quiz quiz = quizMapper.toQuizWithoutId(quizDTO);

      // Save quiz to database
       Quiz savedQuiz = quizRepository.save(quiz);


      // Save questions associated with the quiz to the database
      List<QuestionDTO> questions = quizDTO.getQuestions();
      if (questions != null) {
        for (QuestionDTO questionDTO : questions) {
          questionDTO.setQuizId(savedQuiz.getQuizId());
          questionService.createQuestion(questionDTO);
        }
        logger.info("Questions to quiz " + savedQuiz.getQuizName() + " saved to database.");
      }

      logger.info("Quiz \"" + quiz.getQuizName() + "\" created successfully.");
      QuizDTO savedQuizDTO = quizMapper.toQuizDTO(savedQuiz);
      return ResponseEntity.ok(savedQuizDTO);
    } catch (DataIntegrityViolationException e) {
      logger.severe("Data integrity violation occurred while creating quiz: " + e.getMessage());
      logger.severe("One or more fields in the quiz are invalid.");
      return ResponseEntity.status(HttpStatus.BAD_REQUEST).build();
    } catch (Exception e) {
      System.out.println(e.getClass().getSimpleName());
      logger.severe("An error occurred while creating quiz: " + e.getMessage());
      return ResponseEntity.status(500).build();
    }
  }

  public ResponseEntity<String> deleteQuiz(Long quizId) {
    try {
      deleteQuizFromQuizId(quizId);
      logger.info("Quiz with id " + quizId + " deleted successfully.");
      return ResponseEntity.ok("Quiz deleted successfully.");
    } catch (Exception e) {
      logger.severe("An error occurred while deleting quiz with id " + quizId + ": " + e.getMessage());
      return ResponseEntity.status(500).build();
    }
  }

  public void deleteQuizFromQuizId(Long quizId) {
    try {
      // Delete questions associated with the quiz
      List<MultipleChoiceQuestion> multipleChoiceQuestions = (List<MultipleChoiceQuestion>) multipleChoiceRepository.findAllByQuiz_QuizId(quizId);
      List<TextInputQuestion> textInputQuestions = (List<TextInputQuestion>) textInputRepository.findAllByQuiz_QuizId(quizId);
      List<DragDropQuestionDAO> dragDropQuestions = (List<DragDropQuestionDAO>) dragDropRepository.findAllByQuiz_QuizId(quizId);
      List<TrueFalseQuestionDAO> trueFalseQuestions = (List<TrueFalseQuestionDAO>) trueFalseRepository.findAllByQuiz_QuizId(quizId);

      if (multipleChoiceQuestions != null) {
        multipleChoiceRepository.deleteAll(multipleChoiceQuestions);
      }
      if (textInputQuestions != null) {
        textInputRepository.deleteAll(textInputQuestions);
      }
      if (dragDropQuestions != null) {
        dragDropRepository.deleteAll(dragDropQuestions);
      }
      if (trueFalseQuestions != null) {
        trueFalseRepository.deleteAll(trueFalseQuestions);
      }

      // Delete quiz
      quizRepository.deleteByQuizId(quizId);
    } catch (Exception e) {
      logger.severe("An error occurred while deleting quiz with id " + quizId + ": " + e.getMessage());
      throw e;
    }
  }
}
